package com.qiqiao.ssm.dao.mapper;

import com.qiqiao.ssm.dao.model.SinaUsers;

public interface SinaUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sina_users
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    int deleteByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sina_users
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    int insert(SinaUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sina_users
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    int insertSelective(SinaUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sina_users
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    SinaUsers selectByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sina_users
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    int updateByPrimaryKeySelective(SinaUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sina_users
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    int updateByPrimaryKey(SinaUsers record);
}