package com.qiqiao.ssm.dao.mapper;

import com.qiqiao.ssm.dao.model.SysParams;

public interface SysParamsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_params
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    int deleteByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_params
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    int insert(SysParams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_params
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    int insertSelective(SysParams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_params
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    SysParams selectByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_params
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    int updateByPrimaryKeySelective(SysParams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_params
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    int updateByPrimaryKey(SysParams record);
}