package com.qiqiao.ssm.dao.mapper;

import com.qiqiao.ssm.dao.model.SysUsers;

public interface SysUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    int deleteByPrimaryKey(String suid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    int insert(SysUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    int insertSelective(SysUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    SysUsers selectByPrimaryKey(String suid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    int updateByPrimaryKeySelective(SysUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    int updateByPrimaryKey(SysUsers record);
}