package com.qiqiao.ssm.dao.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.qiqiao.ssm.dao.model.Tweets;

public interface TweetsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tweets
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    int deleteByPrimaryKey(Long tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tweets
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    int insert(Tweets record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tweets
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    int insertSelective(Tweets record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tweets
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    Tweets selectByPrimaryKey(Long tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tweets
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    int updateByPrimaryKeySelective(Tweets record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tweets
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    int updateByPrimaryKey(Tweets record);
    
    int selectCount();
    
    List<Tweets> selectByTime(@Param("startTime") String startTime, @Param("endTime") String endTime);
}