package com.qiqiao.ssm.dao.mapper;

import com.qiqiao.ssm.dao.model.TweetUsers;

public interface TweetUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tweet_users
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    int deleteByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tweet_users
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    int insert(TweetUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tweet_users
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    int insertSelective(TweetUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tweet_users
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    TweetUsers selectByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tweet_users
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    int updateByPrimaryKeySelective(TweetUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tweet_users
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    int updateByPrimaryKey(TweetUsers record);
    
    int selectCount();
}