package com.qiqiao.ssm.dao.model;

public class SinaUsers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sina_users.sid
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    private String sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sina_users.Pwd
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sina_users.Avaiable
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    private Boolean avaiable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sina_users.Reason
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    private String reason;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sina_users.sid
     *
     * @return the value of sina_users.sid
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sina_users.sid
     *
     * @param sid the value for sina_users.sid
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sina_users.Pwd
     *
     * @return the value of sina_users.Pwd
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sina_users.Pwd
     *
     * @param pwd the value for sina_users.Pwd
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sina_users.Avaiable
     *
     * @return the value of sina_users.Avaiable
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public Boolean getAvaiable() {
        return avaiable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sina_users.Avaiable
     *
     * @param avaiable the value for sina_users.Avaiable
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public void setAvaiable(Boolean avaiable) {
        this.avaiable = avaiable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sina_users.Reason
     *
     * @return the value of sina_users.Reason
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sina_users.Reason
     *
     * @param reason the value for sina_users.Reason
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }
}