package com.qiqiao.ssm.dao.model;

public class SysLogs {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_logs.Lid
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    private Integer lid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_logs.LogTime
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    private String logtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_logs.UserCount
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    private Integer usercount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_logs.TweetCount
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    private Integer tweetcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_logs.MsgType
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    private String msgtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_logs.Message
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_logs.ProcessID
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    private Long processid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_logs.Lid
     *
     * @return the value of sys_logs.Lid
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public Integer getLid() {
        return lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_logs.Lid
     *
     * @param lid the value for sys_logs.Lid
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public void setLid(Integer lid) {
        this.lid = lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_logs.LogTime
     *
     * @return the value of sys_logs.LogTime
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public String getLogtime() {
        return logtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_logs.LogTime
     *
     * @param logtime the value for sys_logs.LogTime
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public void setLogtime(String logtime) {
        this.logtime = logtime == null ? null : logtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_logs.UserCount
     *
     * @return the value of sys_logs.UserCount
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public Integer getUsercount() {
        return usercount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_logs.UserCount
     *
     * @param usercount the value for sys_logs.UserCount
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public void setUsercount(Integer usercount) {
        this.usercount = usercount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_logs.TweetCount
     *
     * @return the value of sys_logs.TweetCount
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public Integer getTweetcount() {
        return tweetcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_logs.TweetCount
     *
     * @param tweetcount the value for sys_logs.TweetCount
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public void setTweetcount(Integer tweetcount) {
        this.tweetcount = tweetcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_logs.MsgType
     *
     * @return the value of sys_logs.MsgType
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public String getMsgtype() {
        return msgtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_logs.MsgType
     *
     * @param msgtype the value for sys_logs.MsgType
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public void setMsgtype(String msgtype) {
        this.msgtype = msgtype == null ? null : msgtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_logs.Message
     *
     * @return the value of sys_logs.Message
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_logs.Message
     *
     * @param message the value for sys_logs.Message
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_logs.ProcessID
     *
     * @return the value of sys_logs.ProcessID
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public Long getProcessid() {
        return processid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_logs.ProcessID
     *
     * @param processid the value for sys_logs.ProcessID
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public void setProcessid(Long processid) {
        this.processid = processid;
    }
}