package com.qiqiao.ssm.dao.model;

public class SysParams {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_params.Pid
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_params.ParamCode
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    private String paramcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_params.ParamName
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    private String paramname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_params.ParamValue
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    private String paramvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_params.Enabled
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    private Boolean enabled;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_params.Pid
     *
     * @return the value of sys_params.Pid
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_params.Pid
     *
     * @param pid the value for sys_params.Pid
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_params.ParamCode
     *
     * @return the value of sys_params.ParamCode
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public String getParamcode() {
        return paramcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_params.ParamCode
     *
     * @param paramcode the value for sys_params.ParamCode
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public void setParamcode(String paramcode) {
        this.paramcode = paramcode == null ? null : paramcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_params.ParamName
     *
     * @return the value of sys_params.ParamName
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public String getParamname() {
        return paramname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_params.ParamName
     *
     * @param paramname the value for sys_params.ParamName
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public void setParamname(String paramname) {
        this.paramname = paramname == null ? null : paramname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_params.ParamValue
     *
     * @return the value of sys_params.ParamValue
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public String getParamvalue() {
        return paramvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_params.ParamValue
     *
     * @param paramvalue the value for sys_params.ParamValue
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public void setParamvalue(String paramvalue) {
        this.paramvalue = paramvalue == null ? null : paramvalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_params.Enabled
     *
     * @return the value of sys_params.Enabled
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_params.Enabled
     *
     * @param enabled the value for sys_params.Enabled
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }
}