package com.qiqiao.ssm.dao.model;

public class SysUsers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_users.suid
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    private String suid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_users.Suname
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    private String suname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_users.Pwd
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    private String pwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_users.suid
     *
     * @return the value of sys_users.suid
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public String getSuid() {
        return suid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_users.suid
     *
     * @param suid the value for sys_users.suid
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public void setSuid(String suid) {
        this.suid = suid == null ? null : suid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_users.Suname
     *
     * @return the value of sys_users.Suname
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public String getSuname() {
        return suname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_users.Suname
     *
     * @param suname the value for sys_users.Suname
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public void setSuname(String suname) {
        this.suname = suname == null ? null : suname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_users.Pwd
     *
     * @return the value of sys_users.Pwd
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_users.Pwd
     *
     * @param pwd the value for sys_users.Pwd
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }
}