package com.qiqiao.ssm.dao.model;

public class Tweets {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tweets.tid
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    private Long tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tweets.Mid
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    private String mid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tweets.Text
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tweets.Time
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    private String time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tweets.Uid
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tweets.RegPostTime
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    private String regposttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tweets.RepostCommentCount
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    private Integer repostcommentcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tweets.ShareCount
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    private Integer sharecount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tweets.AttributesCount
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    private Integer attributescount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tweets.Rumor
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    private Boolean rumor;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tweets.tid
     *
     * @return the value of tweets.tid
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public Long getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tweets.tid
     *
     * @param tid the value for tweets.tid
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public void setTid(Long tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tweets.Mid
     *
     * @return the value of tweets.Mid
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public String getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tweets.Mid
     *
     * @param mid the value for tweets.Mid
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public void setMid(String mid) {
        this.mid = mid == null ? null : mid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tweets.Text
     *
     * @return the value of tweets.Text
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tweets.Text
     *
     * @param text the value for tweets.Text
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tweets.Time
     *
     * @return the value of tweets.Time
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tweets.Time
     *
     * @param time the value for tweets.Time
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tweets.Uid
     *
     * @return the value of tweets.Uid
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tweets.Uid
     *
     * @param uid the value for tweets.Uid
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tweets.RegPostTime
     *
     * @return the value of tweets.RegPostTime
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public String getRegposttime() {
        return regposttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tweets.RegPostTime
     *
     * @param regposttime the value for tweets.RegPostTime
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public void setRegposttime(String regposttime) {
        this.regposttime = regposttime == null ? null : regposttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tweets.RepostCommentCount
     *
     * @return the value of tweets.RepostCommentCount
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public Integer getRepostcommentcount() {
        return repostcommentcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tweets.RepostCommentCount
     *
     * @param repostcommentcount the value for tweets.RepostCommentCount
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public void setRepostcommentcount(Integer repostcommentcount) {
        this.repostcommentcount = repostcommentcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tweets.ShareCount
     *
     * @return the value of tweets.ShareCount
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public Integer getSharecount() {
        return sharecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tweets.ShareCount
     *
     * @param sharecount the value for tweets.ShareCount
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public void setSharecount(Integer sharecount) {
        this.sharecount = sharecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tweets.AttributesCount
     *
     * @return the value of tweets.AttributesCount
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public Integer getAttributescount() {
        return attributescount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tweets.AttributesCount
     *
     * @param attributescount the value for tweets.AttributesCount
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public void setAttributescount(Integer attributescount) {
        this.attributescount = attributescount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tweets.Rumor
     *
     * @return the value of tweets.Rumor
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public Boolean getRumor() {
        return rumor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tweets.Rumor
     *
     * @param rumor the value for tweets.Rumor
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public void setRumor(Boolean rumor) {
        this.rumor = rumor;
    }
}