package com.qiqiao.ssm.dao.model;

public class TweetUsers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tweet_users.uid
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tweet_users.Verified
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    private Boolean verified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tweet_users.VerifiedType
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    private String verifiedtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tweet_users.VerifiedKind
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    private Integer verifiedkind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tweet_users.Gender
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tweet_users.GeoEnabled
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    private Boolean geoenabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tweet_users.Province
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tweet_users.FollowersCount
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    private Integer followerscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tweet_users.FriendsCount
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    private Integer friendscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tweet_users.BiFollowersCount
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    private Integer bifollowerscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tweet_users.StatusesCount
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    private Integer statusescount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tweet_users.FavouritesCount
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    private Integer favouritescount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tweet_users.Uname
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    private String uname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tweet_users.uid
     *
     * @return the value of tweet_users.uid
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tweet_users.uid
     *
     * @param uid the value for tweet_users.uid
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tweet_users.Verified
     *
     * @return the value of tweet_users.Verified
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public Boolean getVerified() {
        return verified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tweet_users.Verified
     *
     * @param verified the value for tweet_users.Verified
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public void setVerified(Boolean verified) {
        this.verified = verified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tweet_users.VerifiedType
     *
     * @return the value of tweet_users.VerifiedType
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public String getVerifiedtype() {
        return verifiedtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tweet_users.VerifiedType
     *
     * @param verifiedtype the value for tweet_users.VerifiedType
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public void setVerifiedtype(String verifiedtype) {
        this.verifiedtype = verifiedtype == null ? null : verifiedtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tweet_users.VerifiedKind
     *
     * @return the value of tweet_users.VerifiedKind
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public Integer getVerifiedkind() {
        return verifiedkind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tweet_users.VerifiedKind
     *
     * @param verifiedkind the value for tweet_users.VerifiedKind
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public void setVerifiedkind(Integer verifiedkind) {
        this.verifiedkind = verifiedkind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tweet_users.Gender
     *
     * @return the value of tweet_users.Gender
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tweet_users.Gender
     *
     * @param gender the value for tweet_users.Gender
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tweet_users.GeoEnabled
     *
     * @return the value of tweet_users.GeoEnabled
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public Boolean getGeoenabled() {
        return geoenabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tweet_users.GeoEnabled
     *
     * @param geoenabled the value for tweet_users.GeoEnabled
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public void setGeoenabled(Boolean geoenabled) {
        this.geoenabled = geoenabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tweet_users.Province
     *
     * @return the value of tweet_users.Province
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tweet_users.Province
     *
     * @param province the value for tweet_users.Province
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tweet_users.FollowersCount
     *
     * @return the value of tweet_users.FollowersCount
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public Integer getFollowerscount() {
        return followerscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tweet_users.FollowersCount
     *
     * @param followerscount the value for tweet_users.FollowersCount
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public void setFollowerscount(Integer followerscount) {
        this.followerscount = followerscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tweet_users.FriendsCount
     *
     * @return the value of tweet_users.FriendsCount
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public Integer getFriendscount() {
        return friendscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tweet_users.FriendsCount
     *
     * @param friendscount the value for tweet_users.FriendsCount
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public void setFriendscount(Integer friendscount) {
        this.friendscount = friendscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tweet_users.BiFollowersCount
     *
     * @return the value of tweet_users.BiFollowersCount
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public Integer getBifollowerscount() {
        return bifollowerscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tweet_users.BiFollowersCount
     *
     * @param bifollowerscount the value for tweet_users.BiFollowersCount
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public void setBifollowerscount(Integer bifollowerscount) {
        this.bifollowerscount = bifollowerscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tweet_users.StatusesCount
     *
     * @return the value of tweet_users.StatusesCount
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public Integer getStatusescount() {
        return statusescount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tweet_users.StatusesCount
     *
     * @param statusescount the value for tweet_users.StatusesCount
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public void setStatusescount(Integer statusescount) {
        this.statusescount = statusescount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tweet_users.FavouritesCount
     *
     * @return the value of tweet_users.FavouritesCount
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public Integer getFavouritescount() {
        return favouritescount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tweet_users.FavouritesCount
     *
     * @param favouritescount the value for tweet_users.FavouritesCount
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public void setFavouritescount(Integer favouritescount) {
        this.favouritescount = favouritescount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tweet_users.Uname
     *
     * @return the value of tweet_users.Uname
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tweet_users.Uname
     *
     * @param uname the value for tweet_users.Uname
     *
     * @mbggenerated Mon Jan 23 11:30:55 CST 2017
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }
}